import { Injectable } from '@angular/core';
import { Foods } from '../../about/category/food';
import { Tag } from '../../about/category/Tag';
@Injectable({
  providedIn: 'root'
})
export class FoodService {


  constructor() { }

  getFoodById(id:number){
    return this.getAll().find(food =>food.id == id)!;
  }




  getAllFoodByTag(tag:string) :Foods[]{
    if(tag == 'All')
      return this.getAll()
    else
      return this.getAll().filter(food => food.tags?.includes(tag))
  }

  getAllTag():Tag[]{
    return[
      { name: 'All', count:22},
      { name: 'Indian', count:4},
      { name: 'FastFood', count:2},
      { name: 'Pizza', count:3},
      { name: 'Chinese', count:1},
      { name: 'Noodles', count:1},
      { name: 'Desserts', count:3},
      { name: 'Chicken', count:12},
      { name: 'Cakes', count:1},
      { name: 'Burger', count:2},
      { name: 'Sandwich', count:1},
      { name: 'Chats', count:2},
      { name: 'Bajji', count:1},
      
    ];
  }

  getAll():Foods[]{
    return [
      { id: 11,
        name: 'Panner Masala',
        cookTime: '10-20',
        price:8,
        favorite:true,
        origins:['Indian cuisine'],
        stars:4.5,
        imageUrl: '/food11.jpg',
        tags:['All','Indian','panner'],
        nameWithEmoji: 'Panner Masala 🍲',
        ingredents: "Paneer, onions, tomatoes, green chilies, ginger-garlic paste, garam masala, cumin, coriander powder, turmeric, and fresh cilantro:",
        recipe: "Onions, ginger-garlic paste, and spices, then add tomatoes and cooked until soft; stir in cubed paneer and cooked until heated through, garnishing with cilantro before serving.",
     },
      { id: 13,
        name: 'North Indian Meals',
        cookTime: '20-25',
        price:22,
        favorite:false,
        origins:['Indian cuisine'],
        stars:5.0,
        imageUrl: '/food13.jpg',
        tags:['All','Indian','meals','north'],
        nameWithEmoji: 'North Indian Meals 🍱',
        ingredents: "Rice, wheat flour, lentils, vegetables, ghee, paneer, spices (cumin, coriander, garam masala, turmeric), yogurt, oil",
       recipe: "cooked rice or roti, prepare curry by sautéing vegetables or paneer with spices, add yogurt or ghee to enhance flavor, serve with dal and salad."
      },
     
    { id: 2,
      name: 'French fries',
      cookTime: '10-20',
      price:5,
      favorite:false,
      origins:['American cuisine'],
      stars:4.5,
      imageUrl: '/food2.jpg',
      tags:['All','FastFood','fries','Freanch fries'],
      nameWithEmoji: 'French fries 🍟',
      ingredents: "Potatoes, vegetable oil, salt.",
      recipe: "Cut potatoes into sticks, soak in water, pat dry, fry in hot oil until golden brown, and season with salt.",
    },
    { id: 3,
      name: 'Cheese Pizza',
      cookTime: '10-20',
      price:7,
      favorite:true,
      origins:['American cuisine'],
      stars:4.3,
      imageUrl: '/food3.jpg',
      tags:['All','Pizza','cheese'],
      nameWithEmoji: 'Cheese Pizza 🧀🍕',
      ingredents: "1 pizza dough, 1 cup pizza sauce, 2 cups shredded mozzarella cheese, 1 tablespoon olive oil, 1 teaspoon dried oregano, salt and pepper to taste.",
      recipe: "Preheat the oven to 475°F (245°C), spread sauce on the dough, sprinkle cheese and oregano, then bake for 12-15 minutes until golden brown.",
    },
   
    { id: 5,
      name: 'Assorted Cup Cakes',
      cookTime: '10-20',
      price:15,
      favorite:false,
      origins:['American cuisine'],
      stars:3.8,
      imageUrl: '/food5.jpg',
      tags:['All','cup cakes','Cakes'],
      nameWithEmoji: 'Assorted Cup Cakes 🧁',
      ingredents: "1 ½ cups all-purpose flour, 1 cup sugar, ½ cup unsalted butter, 2 eggs, ½ cup milk, 1 ½ tsp baking powder, 1 tsp vanilla extract, and assorted toppings (e.g., sprinkles, chocolate chips, fruit).",
      recipe: "Preheat the oven to 350°F (175°C). In a bowl, cream the butter and sugar, add eggs one at a time, mix in milk and vanilla, then gradually add flour and baking powder; fill cupcake liners and bake for 18-20 minutes.",
    },
    { id: 4,
      name: 'Noodles',
      cookTime: '10-20',
      price:10,
      favorite:false,
      origins:['Chinese cuisine'],
      stars:4.5,
      imageUrl: '/food4.jpg',
      tags:['All','Chinese','Noodles'],
      nameWithEmoji: 'Noodles 🍝',
      ingredents: "200g noodles, 1 tbsp oil, 2 garlic cloves (minced), 1 cup vegetables (carrot, bell pepper), soy sauce to taste, salt, and pepper.",
      recipe: "Cook noodles as per package instructions, sauté garlic and vegetables in oil, combine with noodles, add soy sauce, salt, and pepper, then serve.",
    },
    { id: 6,
      name: 'Strawberry IceCream Dessert',
      cookTime: '10-20',
      price:6,
      favorite:false,
      origins:['American cuisine'],
      stars:4.6,
      imageUrl: '/food6.jpg',
      tags:['All','Desserts','iceCream','strawberry'],
      nameWithEmoji: 'Strawberry IceCream Dessert 🍧',
      ingredents: "2 cups fresh strawberries, 1 cup heavy cream, 1 cup sweetened condensed milk, 1 tsp vanilla extract, and a pinch of salt.",
      recipe: "Blend strawberries and set aside. Whip cream, fold in condensed milk and vanilla, then mix in strawberries; freeze for 4-6 hours until set.",
    },
    { id: 7,
      name: 'Chicken',
      cookTime: '10-20',
      price:10,
      favorite:false,
      origins:['American cuisine'],
      stars:4.0,
      imageUrl: '/food7.jpg',
      tags:['All','Chicken'],
      nameWithEmoji: 'Chicken 🍗',
      ingredents: "2 chicken breasts, 2 tablespoons olive oil, salt, pepper, 1 teaspoon garlic powder, 1 teaspoon paprika, lemon juice.",
      recipe: "Preheat oven to 375°F (190°C). Season chicken with olive oil, salt, pepper, garlic powder, and paprika, then bake for 25-30 minutes until cooked through.",
    },
    { id: 1,
      name: 'Indian Dal',
      cookTime: '10-20',
      price:12,
      favorite:false,
      origins:['Indian cuisine'],
      stars:4.9,
      imageUrl: '/food1.jpg',
      tags:['All','Indian','rice'],
      nameWithEmoji: 'Indian Dal 🍲',
      ingredents: "1 cup lentils (dal), 1 onion (chopped), 2 tomatoes (chopped), 2 green chilies, 1 teaspoon turmeric, 1 teaspoon cumin seeds, salt to taste, 2 tablespoons oil, fresh coriander for garnish.",
      recipe: "Wash lentils and boil them with turmeric and salt. In a separate pan, heat oil, sauté onions, add tomatoes and chilies, cook until soft, mix with lentils, garnish with coriander, and serve hot.",
    },
   
    { id: 12,
      name: 'South Indian Meals',
      cookTime: '20-25',
      price:22,
      favorite:false,
      origins:['Indian cuisine'],
      stars:5.0,
      imageUrl: '/food12.jpg',
      tags:['All','Indian','meals','south'],
      nameWithEmoji: 'South Indian Meals 🍱',
      ingredents: "1 cup rice, 1/4 cup split urad dal, 1/4 cup chana dal, 1 tsp cumin seeds, salt to taste, oil for cooking, water.",
      recipe: "Soak rice and dals for 4-6 hours, then grind to a smooth batter with cumin seeds and salt. Ferment overnight, then pour onto a hot griddle, cook until golden, and serve with chutney.",
    },
    { id: 21,
      name: 'gulab jamun ice-cream',
      cookTime: '5-10',
      price:6,
      favorite:false,
      origins:['Indian cuisine'],
      stars:3.5,
      imageUrl: '/food21.jpg',
      tags:['All','Desserts','iceCream','gulab','jamun'],
      nameWithEmoji: 'gulab jamun ice-cream 🍨',
      ingredents: "2 cups vanilla ice cream, 1 cup gulab jamun (crushed), ½ cup milk, ¼ cup condensed milk, 1 tsp cardamom powder, chopped pistachios for garnish.",
      recipe: "Mix crushed gulab jamun, milk, and cardamom powder into the softened ice cream, then refreeze until firm. Serve scoops garnished with pistachios.",
    },
   
    { id: 10,
      name: 'Rasmalai',
      cookTime: '10-20',
      price:3,
      favorite:true,
      origins:['Indian cuisine'],
      stars:4.0,
      imageUrl: '/food10.jpg',
      tags:['All','Desserts','Rasmalai'],
      nameWithEmoji: 'Rasmalai 🍨',
      ingredents: "1 cup ricotta cheese, 1 cup milk, 1/2 cup sugar, 1/4 tsp cardamom powder, 1/2 cup water, chopped pistachios and almonds for garnishing.",
      recipe: "Mix ricotta cheese, sugar, and cardamom; shape into discs. Boil milk with water and sugar, add discs, cook until fluffy, and garnish with nuts.",
    },
    { id: 14,
      name: 'Pani Puri',
      cookTime: '5-10',
      price:6,
      favorite:false,
      origins:['Indian cuisine'],
      stars:4.2,
      imageUrl: '/food14.jpg',
      tags:['All','pani','puri','Chats'],
      nameWithEmoji: 'Pani Puri 🧆🥙',
      ingredents: "Semolina, all-purpose flour, baking soda, salt, water, tamarind, mint leaves, coriander, green chilies, boiled potatoes, chickpeas, spices.",
      recipe: "Mix semolina, flour, baking soda, and salt; knead into a dough, roll into small puris, fry until crispy. Prepare spiced water with tamarind, mint, coriander, and chilies; serve puris filled with potato, chickpeas, and spiced water.",
    },
    { id: 15,
      name: 'Dahi Puri',
      cookTime: '10-15',
      price:7,
      favorite:false,
      origins:['Indian cuisine'],
      stars:4.5,
      imageUrl: '/food15.jpg',
      tags:['All','dahi','puri','Chats'],
      nameWithEmoji: 'Dahi Puri 🧆🥙',
      ingredents: "Puri shells, boiled potatoes, chickpeas, yogurt, tamarind chutney, mint chutney, chopped onions, coriander leaves, chaat masala, and sev.",
      recipe: "Stuff puri shells with boiled potatoes and chickpeas, drizzle with yogurt and chutneys, sprinkle with chaat masala, and garnish with onions, coriander, and sev before serving.",
    },
    { id: 16,
      name: 'Bajji',
      cookTime: '5-10',
      price:5,
      favorite:false,
      origins:['Indian cuisine'],
      stars:3.8,
      imageUrl: '/food16.jpg',
      tags:['All','Bajji'],
      nameWithEmoji: 'Bajji',
      ingredents: "4-5 raw bananas or potatoes, 1 cup besan (gram flour), 1 tsp red chili powder, 1/2 tsp turmeric powder, salt to taste, oil for frying.",
      recipe: "Slice the bananas/potatoes, make a batter with besan, spices, and water, dip the slices in the batter, and deep fry until golden brown.",
    },
    { id: 8,
      name: 'Panner Burger',
      cookTime: '10-20',
      price:5,
      favorite:false,
      origins:['American cuisine'],
      stars:4.7,
      imageUrl: '/food8.jpg',
      tags:['All','Burger','fastfood','panner Burger','banner'],
      nameWithEmoji: 'Panner Burger 🍔',
      ingredents: "Paneer, burger buns, lettuce, tomato, onion, cheese, mayonnaise, and spices.",
      recipe: "Grill paneer slices with spices, assemble with veggies and sauces in buns, then serve hot.",
    },
    { id: 9,
      name: 'Veg Sandwich',
      cookTime: '10-20',
      price:4,
      favorite:false,
      origins:['American cuisine'],
      stars:3.5,
      imageUrl: '/food9.jpg',
      tags:['All','Sandwich','veg sandwich'],
      nameWithEmoji: 'Veg Sandwich 🥪',
      ingredents: "Bread slices, cucumber, tomato, lettuce, cheese, mayonnaise, salt, and pepper.",
      recipe: "Spread mayonnaise on bread, layer with cucumber, tomato, lettuce, cheese, sprinkle salt and pepper, and top with another slice of bread.",
    },
    { id: 17,
      name: 'Cheese Nachos',
      cookTime: '10-20',
      price:5,
      favorite:false,
      origins:['American cuisine'],
      stars:4.5,
      imageUrl: '/food17.jpg',
      tags:['All','FastFood','cheese','Nachos'],
      nameWithEmoji: 'Cheese Nachos 🌮',
      ingredents: "Tortilla chips, shredded cheese (cheddar or Monterey Jack), jalapeños, sour cream, guacamole, salsa, black olives (optional)",
      recipe: "Layer tortilla chips on a baking sheet, sprinkle with cheese and jalapeños, then bake at 350°F (175°C) until cheese melts; serve with sour cream, guacamole, and salsa.",
    },
    { id: 18,
      name: 'Cheese Burger',
      cookTime: '10-20',
      price:7,
      favorite:false,
      origins:['American cuisine'],
      stars:4.0,
      imageUrl: '/food18.jpg',
      tags:['All','Burger','cheese'],
      nameWithEmoji: 'Cheese Burger 🍔',
      ingredents: "Ground beef, cheddar cheese, hamburger buns, lettuce, tomato, onion, pickles, ketchup, mustard, salt, and pepper.",
      recipe: "Shape ground beef into patties, season with salt and pepper, grill to desired doneness, melt cheddar cheese on top, and serve in buns with lettuce, tomato, onion, pickles, ketchup, and mustard.",
    },
    { id: 19,
      name: 'Sausage Pizza',
      cookTime: '10-20',
      price:10,
      favorite:false,
      origins:['American cuisine'],
      stars:3.5,
      imageUrl: '/food19.jpg',
      tags:['All','sausage','Pizza'],
      nameWithEmoji: 'Sausage Pizza 🍕',
      ingredents: "Pizza dough, pizza sauce, mozzarella cheese, cooked sausage, sliced bell peppers, onions, and Italian seasoning.",
      recipe: "Preheat the oven to 475°F (245°C). Roll out the dough, spread sauce, add toppings, and bake for 12-15 minutes until golden brown.",
    },
    { id: 20,
      name: 'Vegetable Pizza',
      cookTime: '10-20',
      price:10,
      favorite:false,
      origins:['American cuisine'],
      stars:3.5,
      imageUrl: '/food20.jpg',
      tags:['All','vegetable','Pizza'],
      nameWithEmoji: 'Vegetable Pizza 🍕',
      ingredents: "1 pre-made pizza crust, 1 cup pizza sauce, 1 cup shredded mozzarella cheese, 1/2 cup bell peppers (sliced), 1/2 cup mushrooms (sliced), 1/2 cup onions (sliced), 1/2 cup olives, 1 teaspoon dried oregano.",
      recipe: "Preheat the oven to 450°F (230°C), spread pizza sauce on the crust, top with cheese and vegetables, sprinkle oregano, and bake for 12-15 minutes until the crust is golden.",
    },
    { id: 24,
    name: 'Chicken Nuggets',
    cookTime: '10-20',
    price:4,
    favorite:false,
    origins:['American cuisine'],
    stars:3.5,
    imageUrl: '/food24.jpg',
    tags:['All','Chicken','nuggets'],
    nameWithEmoji: 'Chicken Nuggets 🍗',
    ingredents: "1 lb chicken breast, 1 cup breadcrumbs, 1 egg, 1/2 cup flour, salt, pepper, and oil for frying.",
      recipe: "Cut chicken into bite-sized pieces, dip in flour, then egg, and coat with breadcrumbs; fry until golden brown.",
  },

    ]
  }
}

